### ISSUE TITLE
getting many errors in unity 5.6

### ISSUE THREAD

**Issue by RYG81** [MetaBlastTeam/MetaB5#25]
I am getting more than 298 script errors -
see below
![errors-megablast](https://user-images.githubusercontent.com/10570236/26927598-37927750-4c70-11e7-9b27-e99fd3366c5a.png)

**Comment by Bradr555** [comment]
I just recloned master and I'm not getting any issues or errors with anything, It's also working on all our machines right now and they're all up to date with master. I'm not sure why it's not working for you. Sometimes we have problems where we have to remove all the .meta files and reopen the project and that fixes some weird errors like that. Master is currently clean so I'm not sure what to tell you. If anyone else has a problem with this please let us know and we'll investigate it further.

**Comment by RYG81** [comment]
I tried delete all meta file and re import all.
Also deleted all files re download master file and still same, 265+ errors.
Will wait for some one else to face similar issue.

**Comment by Bradr555** [comment]
I'm sorry you're getting all these errors, I've recloned on 2 different machines and everything is in order. When you open a Scene like Assets/Scenes/Levels/Laboratory does everything look and act normal or is Laboratory empty?

**Comment by Bradr555** [comment]
I've thoroughly tested our repository on multiple machines and multiple networks. There is no problem with our code, this is something on your end. So I'm closing this issue. I'll just add that we use Git LFS for a lot of our files so you might make sure you're doing a `git lfs clone` and that you have LFS on your machine.
